import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
// import { useStickyState } from "../hooks/useStickyState";

const Home: NextPage = () => {
  const router = useRouter();
  const [mount, setMount] = useState(false);
  const [value, setValue] = useState("");
  //   const [_, setPass] = useStickyState("", "pass");
  useEffect(() => {
    setMount(true);
  }, []);

  const handleSubmit = (e: any) => {
    e.preventDefault();
    // @ts-ignore
    window.localStorage.setItem(
      "sdafopfjerhenginadfsvionamsiodnkasfsd-dsf-asdfdasdif",
      value
    );
    router.push("/");
  };

  return (
    <div>
      <Head>
        <title>E408</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout w-full">
        {mount && (
          <form onSubmit={handleSubmit}>
            <input type="text" onChange={(e) => setValue(e.target.value)} />
          </form>
        )}
      </div>
    </div>
  );
};

export default Home;
